<?php
if (!defined('ABSPATH')) { exit; }
get_header();
$rings = [
    ['color' => '#238653', 'position' => '0.05,-1.35,-0.5', 'rotation' => '1.428,0,0.785', 'scale' => '1', 'thickness' => '0.15'],
    ['color' => '#2867a3', 'position' => '1.05,1.65,-1', 'rotation' => '0.2,0.785,1.571', 'scale' => '0.7', 'thickness' => '0.12'],
    ['color' => '#c62828', 'position' => '0.05,1.8,-0.8', 'rotation' => '-0.1,-0.785,-1.428', 'scale' => '0.8', 'thickness' => '0.07'],
    ['color' => '#d4a72c', 'position' => '1.95,0.3,-1.2', 'rotation' => '0.8,-0.55,0.35', 'scale' => '0.84', 'thickness' => '0.1'],
    ['color' => '#7b61a8', 'position' => '-1.2,2.15,-1.35', 'rotation' => '1.15,0.35,-0.75', 'scale' => '0.88', 'thickness' => '0.1'],
];
$materials = [
    ['name' => 'FKM (Viton)', 'code' => 'FKM-902', 'description' => 'High-temperature and chemical resistance for critical applications.', 'temperature' => '-20 to +250°C', 'hardness' => '60 to 90 Shore A', 'image' => 'materials.fkm'],
    ['name' => 'NBR (Nitrile)', 'code' => 'NBR-701', 'description' => 'Balanced oil and fuel resistance for high-volume industrial sealing.', 'temperature' => '-40 to +120°C', 'hardness' => '40 to 90 Shore A', 'image' => 'materials.nbr'],
    ['name' => 'VMQ (Silicone)', 'code' => 'VMQ-605', 'description' => 'Flexible, clean, and weather-stable for food and medical assemblies.', 'temperature' => '-60 to +200°C', 'hardness' => '30 to 80 Shore A', 'image' => 'materials.vmq'],
    ['name' => 'EPDM', 'code' => 'EPDM-804', 'description' => 'Weather, ozone, and steam resistance for outdoor and water systems.', 'temperature' => '-50 to +150°C', 'hardness' => '40 to 90 Shore A', 'image' => 'materials.epdm'],
];
$comparison = [
    ['code' => 'NBR-701', 'material' => 'Nitrile Butadiene Rubber', 'temp' => '+120°C', 'strength' => '14.5 MPa', 'best' => 'Hydraulic oils and general industry'],
    ['code' => 'FKM-902', 'material' => 'Fluorocarbon Rubber', 'temp' => '+250°C', 'strength' => '10.2 MPa', 'best' => 'Chemical processing and fuel systems'],
    ['code' => 'VMQ-605', 'material' => 'Silicone Rubber', 'temp' => '+200°C', 'strength' => '7.8 MPa', 'best' => 'Medical, food, and outdoor equipment'],
    ['code' => 'EPDM-804', 'material' => 'Ethylene Propylene Rubber', 'temp' => '+150°C', 'strength' => '12.1 MPa', 'best' => 'Water, steam, and weather sealing'],
];
$insights = [
    ['category' => 'Technical guide', 'title' => 'How to choose the right O-ring hardness for high-pressure systems', 'excerpt' => 'A practical guide to Shore A, squeeze, and extrusion risk in critical sealing designs.', 'slug' => 'choosing-o-ring-hardness', 'slot' => 'home.insight.hardness'],
    ['category' => 'Industry insight', 'title' => 'Specialized sealing for renewable energy infrastructure', 'excerpt' => 'Material choices that improve reliability across solar, wind, and battery environments.', 'slug' => 'sealing-renewable-energy', 'slot' => 'home.insight.renewable'],
    ['category' => 'Company update', 'title' => 'Expanded direct shipping routes to North America and the EU', 'excerpt' => 'New logistics partnerships shorten lead times while preserving batch-level traceability.', 'slug' => 'global-shipping-update', 'slot' => 'home.insight.shipping'],
];
?>
<main>
<section class="oubei-hero oubei-hero--reference"><div class="oubei-hero__canvas" data-oubei-hero aria-hidden="true"><?php foreach ($rings as $ring) : ?><span data-oubei-ring data-ring-color="<?php echo esc_attr($ring['color']); ?>" data-ring-position="<?php echo esc_attr($ring['position']); ?>" data-ring-rotation="<?php echo esc_attr($ring['rotation']); ?>" data-ring-scale="<?php echo esc_attr($ring['scale']); ?>" data-ring-thickness="<?php echo esc_attr($ring['thickness']); ?>"></span><?php endforeach; ?></div><div class="oubei-hero__veil" aria-hidden="true"></div><div class="oubei-container oubei-hero__inner"><div class="oubei-hero__copy"><div class="oubei-certification">✓ <span>ISO 9001:2015 Certified Manufacturer</span></div><h1>Precision Rubber Sealing Solutions.</h1><p class="lede">Advanced rubber and plastic components for global automotive, aerospace, and industrial applications. More than 20 years of manufacturing leadership.</p><div class="oubei-hero__actions"><a class="button button--accent" href="<?php echo esc_url(home_url('/products')); ?>">Browse catalog <span aria-hidden="true">→</span></a><a class="button button--outline" href="<?php echo esc_url(home_url('/materials')); ?>">Technical specs</a></div></div></div><div class="oubei-trust-strip"><div class="oubei-container oubei-trust-grid"><?php foreach (['20+ years experience','Global delivery','R&D lab tested','ISO 9001 certified'] as $trust) : ?><div><?php echo esc_html($trust); ?></div><?php endforeach; ?></div></div></section>
<section class="oubei-section oubei-section--white"><div class="oubei-container"><div class="oubei-section-heading oubei-section-heading--split"><div><p class="eyebrow">Material engineering</p><h2>Technical Material Categories</h2><p>Optimized compounds engineered for extreme temperatures, pressure, and chemical resistance.</p></div><div class="oubei-heading-actions"><a href="<?php echo esc_url(home_url('/materials')); ?>">View all materials →</a><div class="material-controls" role="group" aria-label="Material slider controls"><button type="button" data-material-prev aria-label="Previous material">←</button><button type="button" data-material-next aria-label="Next material">→</button></div></div></div><div class="oubei-material-slider" data-material-slider><?php foreach ($materials as $index => $material) : $slot = oubei_get_media_slot($material['image']); ?><article class="oubei-material-card<?php echo $index === 0 ? ' is-active' : ''; ?>" data-material-card data-material-index="<?php echo esc_attr((string) $index); ?>"><img src="<?php echo esc_url($slot['url']); ?>" alt="<?php echo esc_attr($slot['alt']); ?>"><div class="oubei-material-shade"></div><button class="oubei-material-trigger" type="button" aria-label="Show <?php echo esc_attr($material['name']); ?> details" aria-expanded="<?php echo $index === 0 ? 'true' : 'false'; ?>"></button><div class="oubei-material-details"><p class="material-code"><?php echo esc_html($material['code']); ?></p><h3><?php echo esc_html($material['name']); ?></h3><p><?php echo esc_html($material['description']); ?></p><dl><div><dt>Temperature</dt><dd><?php echo esc_html($material['temperature']); ?></dd></div><div><dt>Hardness</dt><dd><?php echo esc_html($material['hardness']); ?></dd></div></dl><a href="<?php echo esc_url(home_url('/quote')); ?>">Inquire now →</a></div></article><?php endforeach; ?></div></div></section>
<section class="oubei-section oubei-section--navy"><div class="oubei-container oubei-factory-grid"><div><p class="eyebrow eyebrow--light">Factory capability</p><h2>Advanced Manufacturing Capacity</h2><p>Our facility integrates compression and injection molding technology, zero-defect production controls, and automated optical inspection for critical seals.</p><dl class="oubei-stats"><div><dd>5,000+</dd><dt>Moulds in stock</dt></div><div><dd>24/7</dd><dt>Quality monitoring</dt></div><div><dd>15+</dd><dt>Patented materials</dt></div><div><dd>99.8%</dd><dt>Fulfilment rate</dt></div></dl><a class="button button--outline-light" href="<?php echo esc_url(home_url('/about#facility')); ?>">Facility overview ↓</a></div><div class="oubei-factory-gallery"><div><img src="<?php echo esc_url(oubei_get_media_slot('home.factory.workshop')['url']); ?>" alt="Oubei rubber molding workshop"></div><div><img src="<?php echo esc_url(oubei_get_media_slot('home.factory.lab')['url']); ?>" alt="Material testing laboratory"></div><div><img src="<?php echo esc_url(oubei_get_media_slot('home.factory.warehouse')['url']); ?>" alt="Finished goods warehouse"></div></div></div></section>
<section class="oubei-section oubei-section--white"><div class="oubei-container"><div class="oubei-section-heading oubei-section-heading--center"><h2>Material Property Comparison</h2><p>Compare structural integrity and performance metrics for our most requested compounds.</p></div><div class="oubei-table-wrap"><table class="oubei-data-table"><thead><tr><th>Material code</th><th>Chemical name</th><th>Max temp.</th><th>Tensile strength</th><th>Best for</th></tr></thead><tbody><?php foreach ($comparison as $row) : ?><tr><td><?php echo esc_html($row['code']); ?></td><td><?php echo esc_html($row['material']); ?></td><td><?php echo esc_html($row['temp']); ?></td><td><?php echo esc_html($row['strength']); ?></td><td><?php echo esc_html($row['best']); ?></td></tr><?php endforeach; ?></tbody></table></div></div></section>
<section class="oubei-section oubei-section--muted"><div class="oubei-container"><div class="oubei-section-heading oubei-section-heading--center"><h2>Industry Insights</h2><p>Practical guidance from our engineering and supply teams.</p></div><div class="oubei-insight-grid"><?php foreach ($insights as $insight) : $slot = oubei_get_media_slot($insight['slot']); ?><article class="oubei-insight-card"><div class="oubei-insight-image"><img src="<?php echo esc_url($slot['url']); ?>" alt="<?php echo esc_attr($slot['alt']); ?>"></div><p class="insight-category"><?php echo esc_html($insight['category']); ?></p><h3><?php echo esc_html($insight['title']); ?></h3><p><?php echo esc_html($insight['excerpt']); ?></p><a href="<?php echo esc_url(home_url('/resources/' . $insight['slug'])); ?>">Read insight</a></article><?php endforeach; ?></div></div></section>
<section class="oubei-final-cta"><div class="oubei-container"><div><p class="eyebrow">Engineering support</p><h2>Have a drawing or sealing challenge?</h2></div><a class="button button--accent" href="<?php echo esc_url(home_url('/quote')); ?>">Request a technical review <span aria-hidden="true">→</span></a></div></section>
</main>
<?php get_footer();
