<?php
get_header();
$gate = oubei_get_media_slot('about.gate');
$journey = [
    ['2022', 'Company founded', 'Xingtai Oubei was established in Hebei as a specialist manufacturer of high-performance rubber products for demanding service conditions.', 'about.history.factory'],
    ['12K+', 'Integrated production base', 'A facility of more than 12,000 square meters brings production, testing, warehousing, and export preparation into one coordinated operation.', 'about.history.warehouse'],
    ['TODAY', 'Technical growth', 'A dedicated R&D team continues to refine material formulations and manufacturing processes for complex custom applications worldwide.', 'about.history.team'],
];
$facilities = [
    ['Precision mold workshop', 'Tooling review and controlled mold fabrication support complex geometries and repeatable dimensional performance.', 'about.capability', 'home.factory.workshop'],
    ['Material testing laboratory', 'In-house equipment supports physical property checks, dimensional verification, and formulation development.', 'about.team.1', 'home.factory.lab'],
    ['Production capacity', 'Compression and molding resources are organized for samples, custom lots, and stable repeat-order production.', 'about.team.2', 'home.factory.workshop'],
];
$team = [
    ['Leadership & strategy', 'Long-term customer value and technical investment', 'about.team.1'],
    ['Global sales', 'Responsive export communication and project coordination', 'about.team.2'],
    ['Materials engineering', 'Compound development and application problem solving', 'about.team.3'],
    ['Operations', 'Quality, planning, and reliable order execution', 'about.team.4'],
];
?>
<main>
<section class="oubei-about-hero" style="background-image:linear-gradient(90deg,rgba(6,37,74,.88),rgba(6,37,74,.42)),url('<?php echo esc_url($gate['url']); ?>')"><div class="oubei-container"><span class="oubei-certification">Founded 2022</span><h1>Engineering Excellence in Rubber &amp; Plastic</h1><p>Xingtai Oubei specializes in the R&amp;D, production, and supply of high-performance rubber products for severe chemical, thermal, and industrial operating conditions.</p><div class="oubei-hero__actions"><a class="button button--accent" href="#quality">View certifications →</a><a class="button button--outline" href="#facility">Our facilities</a></div></div></section>

<section id="quality" class="oubei-section oubei-quality"><div class="oubei-container"><h2 class="screen-reader-text">Quality certifications and documentation</h2><div class="oubei-badge-grid"><?php foreach (['about.quality.1','about.quality.2','about.quality.3','about.quality.4','about.quality.5'] as $i => $key) : $slot = oubei_get_media_slot($key); ?><figure><img src="<?php echo esc_url($slot['url']); ?>" alt="<?php echo esc_attr($slot['alt']); ?>"><figcaption><?php echo esc_html(['ISO 9001 quality system','SGS quality verification','RoHS compliance','Automotive quality controls','International audit readiness'][$i]); ?></figcaption></figure><?php endforeach; ?></div><div class="oubei-section-heading"><div><p class="eyebrow">Verified documents</p><h2>Quality records on file</h2></div><p>Available documents can be supplied with project and vendor qualification reviews.</p></div><div class="oubei-certificate-grid"><?php foreach (['about.certificate.1','about.certificate.2','about.certificate.3'] as $i => $key) : $certificate = oubei_get_media_slot($key); ?><figure><img src="<?php echo esc_url($certificate['url']); ?>" alt="<?php echo esc_attr($certificate['alt']); ?>"><figcaption><?php echo esc_html(['Credit management certificate','Environmental management system','Quality management system'][$i]); ?></figcaption></figure><?php endforeach; ?></div></div></section>

<section class="oubei-section"><div class="oubei-container oubei-about-values"><article class="oubei-value oubei-value--dark"><p class="eyebrow eyebrow--light">Our mission</p><h2>Solve demanding applications with reliable rubber engineering.</h2><p>We deliver premium components and tailored solutions through focused material development, controlled manufacturing, and practical technical support.</p></article><article class="oubei-value"><p class="eyebrow">Our vision</p><h2>Trusted global source for elastomer components.</h2><p>Materials expertise, dependable delivery, and continuous improvement.</p></article><article class="oubei-value"><p class="eyebrow">Quality first</p><h3>Controlled checks at every stage</h3><p>Requirements are translated into controlled checks from incoming material to final packing.</p></article><article class="oubei-value"><p class="eyebrow">Innovation &amp; R&amp;D</p><h3>Formulas for complex service</h3><p>A dedicated team optimizes FFKM, HNBR, FKM and other performance materials.</p></article></div></section>

<section class="oubei-section oubei-section--muted"><div class="oubei-container"><div class="oubei-section-heading oubei-section-heading--center"><p class="eyebrow">Company development</p><h2>Our Journey</h2><p>A focused path from specialist manufacturing to integrated technical supply.</p></div><div class="oubei-journey"><?php foreach ($journey as $item) : $image = oubei_get_media_slot($item[3]); ?><article><img src="<?php echo esc_url($image['url']); ?>" alt="<?php echo esc_attr($image['alt']); ?>"><div><strong><?php echo esc_html($item[0]); ?></strong><h3><?php echo esc_html($item[1]); ?></h3><p><?php echo esc_html($item[2]); ?></p></div></article><?php endforeach; ?></div></div></section>

<section id="facility" class="oubei-section"><div class="oubei-container"><div class="oubei-section-heading"><div><p class="eyebrow">Factory capability</p><h2>Manufacturing Prowess</h2><p>Our 12,000+ square meter facility integrates production, testing, storage, and order preparation.</p></div><a class="button button--accent" href="<?php echo esc_url(home_url('/quote')); ?>">Discuss capacity →</a></div><div class="oubei-facility-grid"><?php foreach ($facilities as $item) : $primary = oubei_get_media_slot($item[2]); $real = oubei_get_media_slot($item[3]); ?><article><div><img src="<?php echo esc_url($primary['url']); ?>" alt="<?php echo esc_attr($primary['alt']); ?>"><img src="<?php echo esc_url($real['url']); ?>" alt="<?php echo esc_attr($real['alt']); ?>"></div><h3><?php echo esc_html($item[0]); ?></h3><p><?php echo esc_html($item[1]); ?></p></article><?php endforeach; ?></div></div></section>

<section class="oubei-section oubei-section--navy"><div class="oubei-container oubei-global"><div><p class="eyebrow eyebrow--light">Export-ready support</p><h2>Global Customer Reach</h2><p>Technical communication, tailored packing, and coordinated international shipment help customers qualify and repeat complex rubber components with confidence.</p><dl class="oubei-stats"><div><dd>12,000+</dd><dt>Square meter facility</dt></div><div><dd>50+</dd><dt>Experienced staff</dt></div><div><dd>R&amp;D</dd><dt>Dedicated technical team</dt></div><div><dd>Global</dd><dt>Customer support</dt></div></dl></div>
<div class="oubei-global-map" aria-label="Global production and delivery network"><span class="oubei-map-axis oubei-map-axis--vertical" aria-hidden="true"></span><span class="oubei-map-axis oubei-map-axis--horizontal" aria-hidden="true"></span><svg class="oubei-map-globe" viewBox="0 0 240 240" aria-hidden="true"><circle cx="120" cy="120" r="82"></circle><path d="M78 50c-7 28 1 39 25 42 17 2 21 13 22 25 1 14 10 22 22 22 14 0 22-10 22-24 0-14 12-23 34-22M39 112h40c17 0 27 10 27 27v8c0 17 10 27 27 27h8c17 0 27 10 27 27v20M201 157h-40c-17 0-27 10-27 27v37"></path></svg><div class="oubei-map-point oubei-map-point--tl"><span class="oubei-map-icon oubei-map-icon--red">⌖</span><strong>Hebei, China</strong><small>Production base</small></div><div class="oubei-map-point oubei-map-point--tr"><span class="oubei-map-icon">✓</span><strong>Technical review</strong><small>Application support</small></div><div class="oubei-map-point oubei-map-point--bl"><span class="oubei-map-icon">▥</span><strong>Controlled supply</strong><small>Repeat production</small></div><div class="oubei-map-point oubei-map-point--br"><span class="oubei-map-icon">◎</span><strong>Worldwide delivery</strong><small>Export coordination</small></div></div></div></section>

<section class="oubei-section oubei-team-section"><div class="oubei-container"><div class="oubei-section-heading"><div><p class="eyebrow">People behind production</p><h2>Specialist Team</h2><p>Commercial, materials, quality, and operations expertise working around one project brief.</p></div><a class="button button--outline" href="<?php echo esc_url(home_url('/quote')); ?>">Contact our team</a></div><div class="oubei-team-grid"><?php foreach ($team as $member) : $photo = oubei_get_media_slot($member[2]); ?><article><img src="<?php echo esc_url($photo['url']); ?>" alt="<?php echo esc_attr($photo['alt']); ?>"><h3><?php echo esc_html($member[0]); ?></h3><p><?php echo esc_html($member[1]); ?></p></article><?php endforeach; ?></div><p>More than 50 experienced team members</p></div></section>
<section class="oubei-final-cta"><div class="oubei-container"><div><p class="eyebrow">Engineering support</p><h2>Have a drawing or sealing challenge?</h2></div><a class="button button--accent" href="<?php echo esc_url(home_url('/quote')); ?>">Talk to an engineer →</a></div></section>
</main>
<?php get_footer();
