<?php
get_header();
$hero = oubei_get_media_slot('custom.hero');
$workflow = [
    ['01', 'Consultation', 'We review the application, operating media, temperature, pressure, drawing tolerances, and target volume.', '✎'],
    ['02', 'Prototyping', 'CAD/CAM review, mold development, and rapid samples verify geometry and fit before production tooling is released.', '⌗'],
    ['03', 'Compounding', 'NBR, HNBR, FKM, FFKM, EPDM, and silicone formulations are selected around the required service conditions.', '⌬'],
    ['04', 'Mass production', 'Controlled molding, batch inspection, traceable packing, and documented release support repeatable supply.', '▥'],
];
$capabilities = [
    ['Mold design', 'In-house tooling review for complex profiles, insert-molded parts, and precision sealing geometries.', '▦'],
    ['Private labeling', 'Custom kits, identification, labels, and export-ready packaging aligned with your brand and channel.', '◇'],
    ['Quality control', 'Material, dimensional, and visual checks are documented against agreed drawings and acceptance criteria.', '✓'],
    ['Global logistics', 'Consolidated shipments, repeat-order planning, and flexible lot sizes support international supply programs.', '◎'],
];
$case_studies = [
    ['Industrial equipment', 'High-pressure sealing development', 'A custom FKM sealing set was developed around a compact metal housing, combining dimensional review, compound selection, and fit verification before volume release.', 'custom.study.1', ['Drawing-controlled', 'Pressure validated']],
    ['OEM kit fulfillment', 'Clean, traceable private-label supply', 'A repeat-order program combines application-specific silicone components with controlled inspection, labeled inner packs, and export-ready outer packaging.', 'custom.study.2', ['Lot traceability', 'Custom packaging']],
];
?>
<main class="oubei-custom-page">
<section class="oubei-custom-hero"><div class="oubei-container"><div><p class="eyebrow eyebrow--light">Precision engineering</p><h1>Custom O-Ring Sets &amp; OEM/ODM Solutions</h1><p>Tailored sealing solutions for demanding environments. From material selection and tooling to private-label packaging, our team supports the complete design-to-production cycle.</p><div class="oubei-hero__actions"><a class="button button--accent" href="<?php echo esc_url(home_url('/quote')); ?>">Start project inquiry →</a><a class="button button--outline" href="<?php echo esc_url(home_url('/resources')); ?>">Technical data sheets</a></div></div><figure><img src="<?php echo esc_url($hero['url']); ?>" alt="<?php echo esc_attr($hero['alt']); ?>"><figcaption><span>Compound + geometry + finish</span><strong>✓ Drawing controlled</strong></figcaption></figure></div></section>
<section class="oubei-section"><div class="oubei-container"><div class="oubei-section-heading oubei-section-heading--center"><p class="eyebrow">Engineering workflow</p><h2>Design-to-Production Workflow</h2><p>A structured development path keeps application requirements, samples, tooling, and production release aligned.</p></div><ol class="oubei-workflow"><?php foreach ($workflow as $step) : ?><li><div><span><?php echo esc_html($step[0]); ?></span><i aria-hidden="true"><?php echo esc_html($step[3]); ?></i></div><h3><?php echo esc_html($step[1]); ?></h3><p><?php echo esc_html($step[2]); ?></p></li><?php endforeach; ?></ol></div></section>
<section class="oubei-section oubei-section--muted"><div class="oubei-container oubei-custom-engineering"><div><p class="eyebrow">Compound engineering</p><h2>Advanced Material Selection Guide</h2><p>Seal life depends on the complete service environment. These ranges are starting points; final selection is confirmed against media, pressure, motion, and regulatory requirements.</p><div class="oubei-table-wrap"><table class="oubei-data-table"><thead><tr><th>Material</th><th>Typical range</th><th>Common fit</th></tr></thead><tbody><?php foreach ([['NBR (Nitrile)','-40 to +120°C','Oil and hydraulic fluids'],['HNBR','-40 to +150°C','Heat, wear, and refrigerants'],['FKM','-20 to +250°C','Chemicals, fuels, and heat'],['FFKM','-20 to +320°C','Aggressive chemicals and vacuum'],['VMQ (Silicone)','-60 to +200°C','Food, medical, and low temperature']] as $row) : ?><tr><td><?php echo esc_html($row[0]); ?></td><td><?php echo esc_html($row[1]); ?></td><td><?php echo esc_html($row[2]); ?></td></tr><?php endforeach; ?></tbody></table></div><a class="oubei-text-link" href="<?php echo esc_url(home_url('/materials')); ?>">Compare material families →</a></div><div class="oubei-custom-capabilities"><?php foreach ($capabilities as $capability) : ?><article><span aria-hidden="true"><?php echo esc_html($capability[2]); ?></span><h3><?php echo esc_html($capability[0]); ?></h3><p><?php echo esc_html($capability[1]); ?></p></article><?php endforeach; ?></div></div></section>
<section class="oubei-section"><div class="oubei-container"><div class="oubei-section-heading"><div><p class="eyebrow">Selected programs</p><h2>Case Studies</h2><p>Representative development paths for engineered sealing and repeat-order fulfillment.</p></div></div><div class="oubei-custom-cases"><?php foreach ($case_studies as $index => $study) : $image = oubei_get_media_slot($study[3]); ?><article class="<?php echo $index % 2 ? 'is-reversed' : ''; ?>"><img src="<?php echo esc_url($image['url']); ?>" alt="<?php echo esc_attr($image['alt']); ?>"><div><p class="eyebrow"><?php echo esc_html($study[0]); ?></p><h3><?php echo esc_html($study[1]); ?></h3><p><?php echo esc_html($study[2]); ?></p><div><?php foreach ($study[4] as $fact) : ?><span><?php echo esc_html($fact); ?></span><?php endforeach; ?></div></div></article><?php endforeach; ?></div></div></section>
<section class="oubei-custom-cta"><div class="oubei-container"><span aria-hidden="true">✓</span><h2>Ready to Engineer Your Custom Solution?</h2><p>Send a drawing, operating conditions, or a sample reference. Our team will review feasibility and prepare the next technical step.</p><form action="<?php echo esc_url(home_url('/quote')); ?>" method="get"><label class="screen-reader-text" for="custom-work-email">Work email</label><input id="custom-work-email" name="email" type="email" required placeholder="Your work email"><button class="button button--accent" type="submit">Get started →</button></form><div><small>Drawing review</small><small>Material recommendation</small><small>Production quotation</small></div></div></section>
</main>
<?php get_footer();
