<?php
get_header();
$result = null;
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['oubei_quote_nonce']) && wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['oubei_quote_nonce'])), 'oubei_submit_quote')) {
    $payload = wp_unslash($_POST);
    $brief = array_filter([
        'Project type: ' . sanitize_text_field((string) ($payload['project_type'] ?? '')),
        'Material: ' . sanitize_text_field((string) ($payload['material'] ?? '')),
        'Annual quantity: ' . sanitize_text_field((string) ($payload['quantity'] ?? '')),
        'Application: ' . sanitize_text_field((string) ($payload['application'] ?? '')),
        sanitize_textarea_field((string) ($payload['message'] ?? '')),
    ]);
    $payload['message'] = implode("\n", $brief);
    $result = oubei_handle_inquiry($payload);
}
$email = oubei_get_setting('contact_email', 'sales@example.com');
$phone = oubei_get_setting('contact_phone', '+86 18803390651');
?>
<main class="oubei-quote-page">
<section class="oubei-quote-hero"><div class="oubei-container"><nav class="oubei-breadcrumbs oubei-breadcrumbs--dark"><a href="<?php echo esc_url(home_url('/')); ?>">Home</a><span>›</span><strong>Request a quote</strong></nav><div class="oubei-quote-intro"><div><p class="eyebrow eyebrow--light">Engineering intake / 01</p><h1>Tell us what needs to seal.</h1><p>Share your drawing, operating conditions, and target volumes. Our team will respond with a material and manufacturing path built around the application.</p><div class="oubei-quote-trust"><div><strong>Engineering review</strong><span>One business day for a first response</span></div><div><strong>Secure attachments</strong><span>Drawings up to 10 MB per request</span></div></div><div class="oubei-quote-links"><a href="mailto:<?php echo esc_attr($email); ?>">✉ <?php echo esc_html($email); ?></a><a href="tel:<?php echo esc_attr(preg_replace('/\s+/', '', $phone)); ?>">☎ <?php echo esc_html($phone); ?></a></div></div>
<div class="oubei-quote-form-card"><?php if ($result && $result['success']) : ?><div class="oubei-quote-success"><span>✓</span><p class="eyebrow">Request received</p><h2>Thanks, we have your details.</h2><p>Our engineering sales team will review your brief and reply within one business day.</p><a class="button button--outline" href="<?php echo esc_url(home_url('/resources')); ?>">Browse resources</a></div><?php else : ?><?php if ($result) : ?><p class="oubei-form-error"><?php echo esc_html($result['error']); ?></p><?php endif; ?>
<form method="post" enctype="multipart/form-data" data-quote-form novalidate><?php wp_nonce_field('oubei_submit_quote', 'oubei_quote_nonce'); ?><input type="text" name="website" tabindex="-1" autocomplete="off" aria-hidden="true" class="oubei-honeypot">
<div class="oubei-quote-progress" aria-label="Quote request progress"><div class="is-active" data-quote-progress="1"><b>1</b><span>Project brief</span><small>Tell us what you need</small></div><div data-quote-progress="2"><b>2</b><span>Your details</span><small>Where should we reply?</small></div><div data-quote-progress="3"><b>3</b><span>Review &amp; send</span><small>Confirm your request</small></div></div>
<section data-quote-step="1" aria-labelledby="quote-step-1"><p class="eyebrow">Step 1 of 3</p><h2 id="quote-step-1">Tell us about the part</h2><p>A few constraints help us route your request to the right material and process engineer.</p><div class="oubei-quote-fields"><label>Project type *<select required name="project_type"><option value="">Select one</option><option>New design / prototype</option><option>Replacement part</option><option>Production program</option><option>Technical question</option></select></label><label>Material preference *<select required name="material"><option value="">Choose a family</option><option>NBR / nitrile</option><option>FKM / fluorocarbon</option><option>EPDM</option><option>Silicone / VMQ</option><option>Recommend the best material</option></select></label><label>Estimated annual quantity<select name="quantity"><option value="">Select a range</option><option>Under 1,000 pieces</option><option>1,000 - 10,000 pieces</option><option>10,000 - 100,000 pieces</option><option>Over 100,000 pieces</option></select></label><label>Application or equipment *<input required name="application" placeholder="e.g. hydraulic cylinder, pump, gearbox"></label><label class="oubei-field-wide">What should we know?<textarea name="message" rows="5" placeholder="Pressure, temperature, media, dimensions, target date, or any other useful context"></textarea></label></div><div class="oubei-quote-actions"><button class="button button--accent" type="button" data-quote-next>Continue →</button></div></section>
<section data-quote-step="2" aria-labelledby="quote-step-2" hidden><p class="eyebrow">Step 2 of 3</p><h2 id="quote-step-2">Where should we reply?</h2><p>Your details stay with our engineering sales team and are used only to answer this request.</p><div class="oubei-quote-fields"><label>Full name *<input required name="name" placeholder="Your name"></label><label>Company *<input required name="company" placeholder="Company name"></label><label>Work email *<input required type="email" name="email" placeholder="name@company.com"></label><label>Phone *<input required name="phone" placeholder="+86 319 000 0000"></label><label class="oubei-field-wide">Country<input name="country"></label><label class="oubei-field-wide oubei-file-field">Drawing or reference file <small>(optional)</small><input type="file" name="drawing" accept=".pdf,.step,.stp,.dwg,.dxf,.png,.jpg,.jpeg"><span>Choose a file to attach<br><small>PDF, STEP, STP, DWG, DXF, PNG or JPG up to 10 MB</small></span></label></div><div class="oubei-quote-actions"><button class="button button--outline" type="button" data-quote-back>← Back</button><button class="button button--accent" type="button" data-quote-next>Review request →</button></div></section>
<section data-quote-step="3" aria-labelledby="quote-step-3" hidden><p class="eyebrow">Step 3 of 3</p><h2 id="quote-step-3">Review your request</h2><p>Check the details below. You can go back to edit anything before sending.</p><div class="oubei-quote-review" data-quote-review></div><label class="oubei-consent"><input type="checkbox" required name="consent" value="1"> I agree that Xingtai Oubei may use these details to respond to this technical request.</label><div class="oubei-quote-actions"><button class="button button--outline" type="button" data-quote-back>← Back and edit</button><button class="button button--accent" type="submit">Send request →</button></div></section>
</form><?php endif; ?></div></div></div></section><section class="oubei-quote-note-strip"><div class="oubei-container"><p>✓ No commitment - a technical conversation comes first.</p><a href="<?php echo esc_url(home_url('/resources')); ?>">Read our engineering guides →</a></div></section></main><?php get_footer();
