"use client";
import { useEffect, useState } from "react";
import { AdminField, AdminInput, AdminTextarea } from "@/components/admin/AdminForm";
import { AdminPageHeader, AdminPanel } from "@/components/admin/AdminTable";
type Category = { id:number; name:string; slug:string; description:string; sortOrder:number; isActive:boolean };
export default function CategoriesPage(){ const [items,setItems]=useState<Category[]>([]); const [form,setForm]=useState({name:"",slug:"",description:"",sortOrder:0}); const [editing,setEditing]=useState<number|null>(null); const [message,setMessage]=useState("");
 async function load(){ const r=await fetch("/api/admin/categories"); const j=await r.json(); if(j.data)setItems(j.data); else setMessage(j.error); } // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{load()},[]);
 async function save(e:React.FormEvent){e.preventDefault(); setMessage(""); const r=await fetch(editing?`/api/admin/categories/${editing}`:"/api/admin/categories",{method:editing?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)}); const j=await r.json(); if(!r.ok){setMessage(j.error);return} setMessage("Saved"); setForm({name:"",slug:"",description:"",sortOrder:0});setEditing(null);load();}
 async function remove(id:number){if(!confirm("Delete this category?"))return; const r=await fetch(`/api/admin/categories/${id}`,{method:"DELETE"}); const j=await r.json(); setMessage(r.ok?"Deleted":j.error); if(r.ok)load();}
 return <><AdminPageHeader title="Categories" description="Organize products into searchable catalog groups."/><div className="grid gap-6 xl:grid-cols-[360px_1fr]"><AdminPanel className="p-5"><h2 className="text-lg font-semibold text-[#0b2545]">{editing?"Edit category":"Add category"}</h2><form onSubmit={save} className="mt-5 space-y-4"><AdminField label="Name"><AdminInput required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></AdminField><AdminField label="Slug"><AdminInput value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})}/></AdminField><AdminField label="Description"><AdminTextarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></AdminField><AdminField label="Sort order"><AdminInput type="number" value={form.sortOrder} onChange={e=>setForm({...form,sortOrder:Number(e.target.value)})}/></AdminField><button className="bg-[#0b2545] px-4 py-2 text-sm font-semibold text-white">{editing?"Update":"Create"}</button>{editing&&<button type="button" className="ml-3 px-4 py-2 text-sm" onClick={()=>{setEditing(null);setForm({name:"",slug:"",description:"",sortOrder:0})}}>Cancel</button>}<p className="text-sm text-[#c62828]">{message}</p></form></AdminPanel><AdminPanel className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b border-[#d4dde8] text-xs uppercase text-[#64748b]"><tr><th className="p-4">Name</th><th>Slug</th><th>Status</th><th className="p-4">Actions</th></tr></thead><tbody>{items.map(c=><tr key={c.id} className="border-b border-[#edf1f5]"><td className="p-4 font-medium">{c.name}</td><td>{c.slug}</td><td>{c.isActive?"Active":"Hidden"}</td><td className="p-4"><button className="mr-3 underline" onClick={()=>{setEditing(c.id);setForm({name:c.name,slug:c.slug,description:c.description,sortOrder:c.sortOrder})}}>Edit</button><button className="text-[#c62828] underline" onClick={()=>remove(c.id)}>Delete</button></td></tr>)}</tbody></table></AdminPanel></div></> }
